### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'

### ISSUE THREAD

**Issue by Angelene0226** [hey-it-s-me/CoRPLE#3]
hi, I tried running your code several times, step by step, but every time I encountered this error:
"python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 140, in <module>
    write_version_py()
  File "setup.py", line 69, in write_version_py
    with open('VERSION', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'"
even if this error is solved, there will still be many other environment related errors.
is there a problem with the environment configuration?

**Comment by Minglinhe** [comment]
Me too, this VERSION file keeps throwing errors. Have you managed to fix it?
